### ISSUE TITLE
Running the ClientServerExample with the wrong number of argument does not crash the program

### ISSUE THREAD

**Issue by bonnetn** [LthomasMP/iperf_go#1]
Running the ClientServerExample with the wrong number of argument does not crash the program
```go
	if len(os.Args) != 1 {
		fmt.Println("Wrong argument. Usage: ./ClientServerExample <your_port>")
	}
```

will not crash the program, and result in a cascading sequence of error messages:
`./ClientServerExample` will print
```
Wrong argument. Usage: ./ClientServerExample <your_port>
Conversion failed
[...]
Failed to run server
[...]
```

You can use [log.Fatalf](https://golang.org/pkg/log/#Logger.Fatalf) to panic on errors.

**Comment by bonnetn** [comment]
@LthomasMP please resolve this issue

**Comment by p4zuu** [comment]
Thanks for the advice. Changes done
